-- Migration: Add 20 Predefined ERP Roles with Permissions
-- Created: 2026-06-17
-- Purpose: Initialize RBAC system with comprehensive role-based access control

-- First, ensure the Roles table has the Permissions JSON column
ALTER TABLE "Roles" ADD COLUMN IF NOT EXISTS "Permissions" JSONB DEFAULT '{}';
ALTER TABLE "Roles" ADD COLUMN IF NOT EXISTS "IsDeleted" BOOLEAN DEFAULT FALSE;
ALTER TABLE "Roles" ADD COLUMN IF NOT EXISTS "UpdatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP;

-- Create index for role lookups
CREATE INDEX IF NOT EXISTS idx_roles_active ON "Roles"("IsActive", "IsDeleted");

-- Insert 20 Predefined Roles with their permissions
-- Role 1: Super Admin (Full Access)
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  1,
  'Super Admin',
  TRUE,
  '{
    "dashboard": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "users": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "roles": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "companies": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "products": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "categories": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "units": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "warehouses": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "stock": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "stockMovements": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "suppliers": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "purchaseOrders": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "purchaseRequisitions": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "purchaseReturns": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "salesOrders": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "salesQuotations": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "deliveryChallans": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "salesReturns": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "customers": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "brands": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "bom": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "productionOrders": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "expenses": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "approvals": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "dataImportExport": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "racks": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "bins": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "accounts": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "contacts": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "leads": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "opportunities": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "presales": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "cases": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "reports": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "settings": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "chat": {"view": true, "create": true, "edit": true, "delete": true, "export": true}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 2: Company Admin
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  2,
  'Company Admin',
  TRUE,
  '{
    "dashboard": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "users": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "roles": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "companies": {"view": true, "create": false, "edit": true, "delete": false, "export": true},
    "products": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "categories": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "units": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "warehouses": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "stock": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "stockMovements": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "suppliers": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "purchaseOrders": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "purchaseRequisitions": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "purchaseReturns": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "salesOrders": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "salesQuotations": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "deliveryChallans": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "salesReturns": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "customers": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "brands": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "bom": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "productionOrders": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "expenses": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "approvals": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "dataImportExport": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "racks": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "bins": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "accounts": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "contacts": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "leads": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "opportunities": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "presales": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "cases": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "reports": {"view": true, "create": true, "edit": true, "delete": true, "export": true},
    "settings": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "chat": {"view": true, "create": true, "edit": true, "delete": true, "export": true}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 3: Branch Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  3,
  'Branch Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": true, "create": false, "edit": true, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": true, "delete": false, "export": true},
    "stock": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesOrders": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesQuotations": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "deliveryChallans": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesReturns": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "customers": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "expenses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "approvals": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "racks": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bins": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "accounts": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "contacts": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "leads": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "opportunities": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "presales": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "cases": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 4: Inventory Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  4,
  'Inventory Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "categories": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "units": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "warehouses": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "stock": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "suppliers": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesQuotations": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "deliveryChallans": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "customers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "brands": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "racks": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "bins": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 5: Store Keeper
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  5,
  'Store Keeper',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesQuotations": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "deliveryChallans": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "customers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bins": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": false, "edit": false, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 6: Purchase Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  6,
  'Purchase Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "categories": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "units": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "bom": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "productionOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 7: Purchase Executive
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  7,
  'Purchase Executive',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "categories": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "units": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "bom": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "productionOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 8: Sales Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  8,
  'Sales Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseRequisitions": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesOrders": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesQuotations": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "deliveryChallans": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesReturns": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "customers": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "productionOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "contacts": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "leads": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "opportunities": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "presales": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "cases": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 9: Sales Executive
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  9,
  'Sales Executive',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseRequisitions": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesOrders": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "salesQuotations": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "deliveryChallans": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "customers": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "productionOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "contacts": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "leads": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "opportunities": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "presales": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "cases": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "reports": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 10: Production Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  10,
  'Production Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "categories": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "units": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "bom": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 11: Production Supervisor
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  11,
  'Production Supervisor',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": true, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": true, "delete": false, "export": true},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": true, "create": false, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 12: Production Operator
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  12,
  'Production Operator',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": true, "delete": false, "export": true},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": false, "edit": false, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 13: Quality Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  13,
  'Quality Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "categories": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "units": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 14: Quality Inspector
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  14,
  'Quality Inspector',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 15: Finance Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  15,
  'Finance Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesQuotations": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "deliveryChallans": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "customers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "expenses": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "approvals": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "dataImportExport": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "contacts": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "leads": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "opportunities": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "presales": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "cases": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "reports": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 16: Accountant
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  16,
  'Accountant',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseRequisitions": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "purchaseReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesQuotations": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "deliveryChallans": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "salesReturns": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "customers": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "productionOrders": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "expenses": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "approvals": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "dataImportExport": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "contacts": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "leads": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "opportunities": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "presales": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "cases": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "reports": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 17: CRM Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  17,
  'CRM Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseRequisitions": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "productionOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "contacts": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "leads": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "opportunities": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "presales": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "cases": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "reports": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 18: CRM Executive
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  18,
  'CRM Executive',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "categories": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "units": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "warehouses": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stock": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "stockMovements": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "suppliers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseRequisitions": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "bom": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "productionOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "contacts": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "leads": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "opportunities": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "presales": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "cases": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "reports": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 19: HR Manager
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  19,
  'HR Manager',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "users": {"view": true, "create": true, "edit": true, "delete": false, "export": true},
    "roles": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "categories": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "units": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "warehouses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "stock": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "stockMovements": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "suppliers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseRequisitions": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bom": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "productionOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": true, "create": false, "edit": false, "delete": false, "export": true},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": true, "edit": true, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Role 20: Employee
INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
VALUES (
  20,
  'Employee',
  TRUE,
  '{
    "dashboard": {"view": true, "create": false, "edit": false, "delete": false, "export": false},
    "users": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "roles": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "companies": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "products": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "categories": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "units": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "warehouses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "stock": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "stockMovements": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "suppliers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseRequisitions": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "purchaseReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesQuotations": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "deliveryChallans": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "salesReturns": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "customers": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "brands": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bom": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "productionOrders": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "expenses": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "approvals": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "dataImportExport": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "racks": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "bins": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "accounts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "contacts": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "leads": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "opportunities": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "presales": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "cases": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "reports": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "settings": {"view": false, "create": false, "edit": false, "delete": false, "export": false},
    "chat": {"view": true, "create": false, "edit": false, "delete": false, "export": false}
  }'::jsonb,
  NOW(),
  NOW()
) ON CONFLICT ("Id") DO NOTHING;

-- Create AuditLogs table for tracking RBAC changes
CREATE TABLE IF NOT EXISTS "AuditLogs" (
  "Id" SERIAL PRIMARY KEY,
  "UserId" INT REFERENCES "Users"("UserId") ON DELETE SET NULL,
  "RoleId" INT REFERENCES "Roles"("Id") ON DELETE SET NULL,
  "Action" VARCHAR(100) NOT NULL,
  "EntityType" VARCHAR(100) NOT NULL,
  "EntityId" INT,
  "OldValue" JSONB,
  "NewValue" JSONB,
  "IpAddress" VARCHAR(64),
  "UserAgent" TEXT,
  "CreatedAt" TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_audit_logs_user ON "AuditLogs"("UserId");
CREATE INDEX IF NOT EXISTS idx_audit_logs_role ON "AuditLogs"("RoleId");
CREATE INDEX IF NOT EXISTS idx_audit_logs_created ON "AuditLogs"("CreatedAt");
CREATE INDEX IF NOT EXISTS idx_audit_logs_entity ON "AuditLogs"("EntityType", "EntityId");

-- Add comment
COMMENT ON TABLE "AuditLogs" IS 'Tracks all RBAC changes including role and permission modifications';