/**
 * PDF Report Generator
 * Generates HTML-based reports that can be converted to PDF
 */

const generateInvoiceHTML = (invoice, items = []) => {
  const itemRows = items.map(item => `
    <tr>
      <td>${item.ProductName || 'N/A'}</td>
      <td>${item.Quantity || 0}</td>
      <td>₹${(item.UnitPrice || 0).toFixed(2)}</td>
      <td>${item.TaxRate || 0}%</td>
      <td>₹${((item.Quantity || 0) * (item.UnitPrice || 0)).toFixed(2)}</td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    .header { display: flex; justify-content: space-between; border-bottom: 2px solid #4361ee; padding-bottom: 20px; margin-bottom: 20px; }
    .company-name { font-size: 24px; font-weight: bold; color: #4361ee; }
    .invoice-title { font-size: 20px; font-weight: bold; color: #333; }
    .details { display: flex; justify-content: space-between; margin-bottom: 30px; }
    .details div { flex: 1; }
    .details h4 { color: #666; margin-bottom: 5px; font-size: 12px; text-transform: uppercase; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th { background: #4361ee; color: white; padding: 10px; text-align: left; font-size: 12px; }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; font-size: 12px; }
    .total { text-align: right; font-size: 16px; font-weight: bold; color: #4361ee; }
    .footer { text-align: center; color: #999; font-size: 10px; margin-top: 40px; border-top: 1px solid #eee; padding-top: 10px; }
  </style>
</head>
<body>
  <div class="header">
    <div class="company-name">Demo Corp</div>
    <div class="invoice-title">INVOICE</div>
  </div>
  <div class="details">
    <div>
      <h4>Bill To</h4>
      <p>${invoice.CustomerName || 'N/A'}</p>
      <p>${invoice.CustomerEmail || ''}</p>
    </div>
    <div>
      <h4>Invoice Details</h4>
      <p><strong>Invoice #:</strong> ${invoice.InvoiceNumber || 'N/A'}</p>
      <p><strong>Date:</strong> ${invoice.InvoiceDate || new Date().toISOString().split('T')[0]}</p>
      <p><strong>Due Date:</strong> ${invoice.DueDate || 'N/A'}</p>
    </div>
  </div>
  <table>
    <thead>
      <tr><th>Product</th><th>Qty</th><th>Price</th><th>Tax</th><th>Total</th></tr>
    </thead>
    <tbody>
      ${itemRows || '<tr><td colspan="5">No items</td></tr>'}
    </tbody>
  </table>
  <div class="total">Grand Total: ₹${(invoice.GrandTotal || 0).toFixed(2)}</div>
  <div class="footer">Generated by ERP CRM System | ${new Date().toISOString()}</div>
</body>
</html>`;
};

const generateSalesOrderHTML = (order, items = []) => {
  const itemRows = items.map(item => `
    <tr>
      <td>${item.ProductName || 'N/A'}</td>
      <td>${item.Quantity || 0}</td>
      <td>₹${(item.UnitPrice || 0).toFixed(2)}</td>
      <td>₹${((item.Quantity || 0) * (item.UnitPrice || 0)).toFixed(2)}</td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; color: #333; }
    .header { display: flex; justify-content: space-between; border-bottom: 2px solid #4361ee; padding-bottom: 20px; margin-bottom: 20px; }
    .company-name { font-size: 24px; font-weight: bold; color: #4361ee; }
    .order-title { font-size: 20px; font-weight: bold; }
    table { width: 100%; border-collapse: collapse; margin-bottom: 20px; }
    th { background: #4361ee; color: white; padding: 10px; text-align: left; }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; }
    .total { text-align: right; font-size: 16px; font-weight: bold; color: #4361ee; }
  </style>
</head>
<body>
  <div class="header">
    <div class="company-name">Demo Corp</div>
    <div class="order-title">SALES ORDER</div>
  </div>
  <p><strong>Order #:</strong> ${order.OrderNumber || 'N/A'} | <strong>Date:</strong> ${order.OrderDate || new Date().toISOString().split('T')[0]} | <strong>Status:</strong> ${order.Status || 'Pending'}</p>
  <table>
    <thead><tr><th>Product</th><th>Qty</th><th>Price</th><th>Total</th></tr></thead>
    <tbody>${itemRows || '<tr><td colspan="4">No items</td></tr>'}</tbody>
  </table>
  <div class="total">Grand Total: ₹${(order.GrandTotal || 0).toFixed(2)}</div>
</body>
</html>`;
};

const generateStockReportHTML = (products = []) => {
  const rows = products.map(p => `
    <tr>
      <td>${p.ProductName || 'N/A'}</td>
      <td>${p.ProductCode || 'N/A'}</td>
      <td>${p.Quantity || 0}</td>
      <td>${p.ReorderLevel || 0}</td>
      <td style="color: ${(p.Quantity || 0) <= (p.ReorderLevel || 0) ? '#ef4444' : '#10b981'}">
        ${(p.Quantity || 0) <= (p.ReorderLevel || 0) ? 'Low' : 'OK'}
      </td>
    </tr>
  `).join('');

  return `
<!DOCTYPE html>
<html>
<head>
  <style>
    body { font-family: Arial, sans-serif; margin: 40px; }
    h1 { color: #4361ee; }
    table { width: 100%; border-collapse: collapse; }
    th { background: #4361ee; color: white; padding: 10px; text-align: left; }
    td { padding: 8px 10px; border-bottom: 1px solid #eee; }
  </style>
</head>
<body>
  <h1>Stock Report</h1>
  <p>Generated: ${new Date().toISOString()}</p>
  <table>
    <thead><tr><th>Product</th><th>Code</th><th>Stock</th><th>Reorder Level</th><th>Status</th></tr></thead>
    <tbody>${rows}</tbody>
  </table>
</body>
</html>`;
};

module.exports = { generateInvoiceHTML, generateSalesOrderHTML, generateStockReportHTML };