/**
 * Role Seeder Utility
 * 
 * This script initializes the database with the 20 predefined ERP roles
 * and their permissions. Run this script after setting up the database
 * to populate the Roles table with default permissions.
 * 
 * Usage: node scripts/seedRoles.js
 */

const { appPool } = require('../config/db');

const ROLES = [
  {
    id: 1,
    name: 'Super Admin',
    permissions: {
      dashboard: { view: true, create: true, edit: true, delete: true, export: true },
      users: { view: true, create: true, edit: true, delete: true, export: true },
      roles: { view: true, create: true, edit: true, delete: true, export: true },
      companies: { view: true, create: true, edit: true, delete: true, export: true },
      products: { view: true, create: true, edit: true, delete: true, export: true },
      categories: { view: true, create: true, edit: true, delete: true, export: true },
      units: { view: true, create: true, edit: true, delete: true, export: true },
      warehouses: { view: true, create: true, edit: true, delete: true, export: true },
      stock: { view: true, create: true, edit: true, delete: true, export: true },
      stockMovements: { view: true, create: true, edit: true, delete: true, export: true },
      suppliers: { view: true, create: true, edit: true, delete: true, export: true },
      purchaseOrders: { view: true, create: true, edit: true, delete: true, export: true },
      purchaseRequisitions: { view: true, create: true, edit: true, delete: true, export: true },
      purchaseReturns: { view: true, create: true, edit: true, delete: true, export: true },
      salesOrders: { view: true, create: true, edit: true, delete: true, export: true },
      salesQuotations: { view: true, create: true, edit: true, delete: true, export: true },
      deliveryChallans: { view: true, create: true, edit: true, delete: true, export: true },
      salesReturns: { view: true, create: true, edit: true, delete: true, export: true },
      customers: { view: true, create: true, edit: true, delete: true, export: true },
      brands: { view: true, create: true, edit: true, delete: true, export: true },
      bom: { view: true, create: true, edit: true, delete: true, export: true },
      productionOrders: { view: true, create: true, edit: true, delete: true, export: true },
      expenses: { view: true, create: true, edit: true, delete: true, export: true },
      approvals: { view: true, create: true, edit: true, delete: true, export: true },
      dataImportExport: { view: true, create: true, edit: true, delete: true, export: true },
      racks: { view: true, create: true, edit: true, delete: true, export: true },
      bins: { view: true, create: true, edit: true, delete: true, export: true },
      accounts: { view: true, create: true, edit: true, delete: true, export: true },
      contacts: { view: true, create: true, edit: true, delete: true, export: true },
      leads: { view: true, create: true, edit: true, delete: true, export: true },
      opportunities: { view: true, create: true, edit: true, delete: true, export: true },
      presales: { view: true, create: true, edit: true, delete: true, export: true },
      cases: { view: true, create: true, edit: true, delete: true, export: true },
      reports: { view: true, create: true, edit: true, delete: true, export: true },
      settings: { view: true, create: true, edit: true, delete: true, export: true },
      chat: { view: true, create: true, edit: true, delete: true, export: true }
    }
  },
  {
    id: 2,
    name: 'Company Admin',
    permissions: {
      dashboard: { view: true, create: true, edit: true, delete: true, export: true },
      users: { view: true, create: true, edit: true, delete: true, export: true },
      roles: { view: true, create: false, edit: false, delete: false, export: true },
      companies: { view: true, create: false, edit: true, delete: false, export: true },
      products: { view: true, create: true, edit: true, delete: true, export: true },
      categories: { view: true, create: true, edit: true, delete: true, export: true },
      units: { view: true, create: true, edit: true, delete: true, export: true },
      warehouses: { view: true, create: true, edit: true, delete: true, export: true },
      stock: { view: true, create: true, edit: true, delete: true, export: true },
      stockMovements: { view: true, create: true, edit: true, delete: true, export: true },
      suppliers: { view: true, create: true, edit: true, delete: true, export: true },
      purchaseOrders: { view: true, create: true, edit: true, delete: true, export: true },
      purchaseRequisitions: { view: true, create: true, edit: true, delete: true, export: true },
      purchaseReturns: { view: true, create: true, edit: true, delete: true, export: true },
      salesOrders: { view: true, create: true, edit: true, delete: true, export: true },
      salesQuotations: { view: true, create: true, edit: true, delete: true, export: true },
      deliveryChallans: { view: true, create: true, edit: true, delete: true, export: true },
      salesReturns: { view: true, create: true, edit: true, delete: true, export: true },
      customers: { view: true, create: true, edit: true, delete: true, export: true },
      brands: { view: true, create: true, edit: true, delete: true, export: true },
      bom: { view: true, create: true, edit: true, delete: true, export: true },
      productionOrders: { view: true, create: true, edit: true, delete: true, export: true },
      expenses: { view: true, create: true, edit: true, delete: true, export: true },
      approvals: { view: true, create: true, edit: true, delete: true, export: true },
      dataImportExport: { view: true, create: true, edit: true, delete: true, export: true },
      racks: { view: true, create: true, edit: true, delete: true, export: true },
      bins: { view: true, create: true, edit: true, delete: true, export: true },
      accounts: { view: true, create: true, edit: true, delete: true, export: true },
      contacts: { view: true, create: true, edit: true, delete: true, export: true },
      leads: { view: true, create: true, edit: true, delete: true, export: true },
      opportunities: { view: true, create: true, edit: true, delete: true, export: true },
      presales: { view: true, create: true, edit: true, delete: true, export: true },
      cases: { view: true, create: true, edit: true, delete: true, export: true },
      reports: { view: true, create: true, edit: true, delete: true, export: true },
      settings: { view: true, create: false, edit: false, delete: false, export: true },
      chat: { view: true, create: true, edit: true, delete: true, export: true }
    }
  },
  {
    id: 3,
    name: 'Branch Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: true, create: false, edit: true, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: true, edit: true, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: true, delete: false, export: true },
      stock: { view: true, create: true, edit: true, delete: false, export: true },
      stockMovements: { view: true, create: true, edit: true, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseRequisitions: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseReturns: { view: true, create: true, edit: true, delete: false, export: true },
      salesOrders: { view: true, create: true, edit: true, delete: false, export: true },
      salesQuotations: { view: true, create: true, edit: true, delete: false, export: true },
      deliveryChallans: { view: true, create: true, edit: true, delete: false, export: true },
      salesReturns: { view: true, create: true, edit: true, delete: false, export: true },
      customers: { view: true, create: true, edit: true, delete: false, export: true },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: true, create: false, edit: false, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: false, delete: false, export: true },
      expenses: { view: true, create: false, edit: false, delete: false, export: true },
      approvals: { view: true, create: true, edit: true, delete: false, export: true },
      dataImportExport: { view: true, create: false, edit: false, delete: false, export: true },
      racks: { view: true, create: false, edit: false, delete: false, export: true },
      bins: { view: true, create: false, edit: false, delete: false, export: true },
      accounts: { view: true, create: false, edit: false, delete: false, export: true },
      contacts: { view: true, create: false, edit: false, delete: false, export: true },
      leads: { view: true, create: true, edit: true, delete: false, export: true },
      opportunities: { view: true, create: true, edit: true, delete: false, export: true },
      presales: { view: false, create: false, edit: false, delete: false, export: true },
      cases: { view: true, create: false, edit: false, delete: false, export: true },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 4,
    name: 'Inventory Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: true, edit: true, delete: false, export: true },
      categories: { view: true, create: true, edit: true, delete: false, export: true },
      units: { view: true, create: true, edit: true, delete: false, export: true },
      warehouses: { view: true, create: true, edit: true, delete: false, export: true },
      stock: { view: true, create: true, edit: true, delete: false, export: true },
      stockMovements: { view: true, create: true, edit: true, delete: false, export: true },
      suppliers: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseOrders: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseRequisitions: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseReturns: { view: true, create: true, edit: true, delete: false, export: true },
      salesOrders: { view: true, create: false, edit: false, delete: false, export: true },
      salesQuotations: { view: true, create: false, edit: false, delete: false, export: true },
      deliveryChallans: { view: true, create: false, edit: false, delete: false, export: true },
      salesReturns: { view: true, create: false, edit: false, delete: false, export: true },
      customers: { view: true, create: false, edit: false, delete: false, export: true },
      brands: { view: true, create: true, edit: true, delete: false, export: true },
      bom: { view: true, create: false, edit: false, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: false, delete: false, export: true },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: true, create: true, edit: true, delete: false, export: true },
      dataImportExport: { view: true, create: true, edit: true, delete: false, export: true },
      racks: { view: true, create: true, edit: true, delete: false, export: true },
      bins: { view: true, create: true, edit: true, delete: false, export: true },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 5,
    name: 'Store Keeper',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: true, edit: true, delete: false, export: true },
      stockMovements: { view: true, create: true, edit: true, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseRequisitions: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseReturns: { view: true, create: false, edit: false, delete: false, export: true },
      salesOrders: { view: true, create: false, edit: false, delete: false, export: true },
      salesQuotations: { view: true, create: false, edit: false, delete: false, export: true },
      deliveryChallans: { view: true, create: false, edit: false, delete: false, export: true },
      salesReturns: { view: true, create: false, edit: false, delete: false, export: true },
      customers: { view: true, create: false, edit: false, delete: false, export: true },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: true, create: false, edit: false, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: false, delete: false, export: true },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: false, create: false, edit: false, delete: false, export: false },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: true, create: false, edit: false, delete: false, export: true },
      bins: { view: true, create: false, edit: false, delete: false, export: true },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: false, edit: false, delete: false, export: false }
    }
  },
  {
    id: 6,
    name: 'Purchase Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: true, edit: true, delete: false, export: true },
      categories: { view: true, create: true, edit: true, delete: false, export: true },
      units: { view: true, create: true, edit: true, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseOrders: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseRequisitions: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseReturns: { view: true, create: true, edit: true, delete: false, export: true },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: true, edit: true, delete: false, export: true },
      bom: { view: false, create: false, edit: false, delete: false, export: false },
      productionOrders: { view: false, create: false, edit: false, delete: false, export: false },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: true, create: true, edit: true, delete: false, export: true },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 7,
    name: 'Purchase Executive',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: true, edit: true, delete: false, export: true },
      categories: { view: true, create: true, edit: true, delete: false, export: true },
      units: { view: true, create: true, edit: true, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseOrders: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseRequisitions: { view: true, create: true, edit: true, delete: false, export: true },
      purchaseReturns: { view: true, create: true, edit: true, delete: false, export: true },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: true, edit: true, delete: false, export: true },
      bom: { view: false, create: false, edit: false, delete: false, export: false },
      productionOrders: { view: false, create: false, edit: false, delete: false, export: false },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: false, create: false, edit: false, delete: false, export: false },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 8,
    name: 'Sales Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseOrders: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseRequisitions: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseReturns: { view: false, create: false, edit: false, delete: false, export: false },
      salesOrders: { view: true, create: true, edit: true, delete: false, export: true },
      salesQuotations: { view: true, create: true, edit: true, delete: false, export: true },
      deliveryChallans: { view: true, create: true, edit: true, delete: false, export: true },
      salesReturns: { view: true, create: true, edit: true, delete: false, export: true },
      customers: { view: true, create: true, edit: true, delete: false, export: true },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: false, create: false, edit: false, delete: false, export: false },
      productionOrders: { view: false, create: false, edit: false, delete: false, export: false },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: true, create: true, edit: true, delete: false, export: true },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: true, create: true, edit: true, delete: false, export: true },
      contacts: { view: true, create: true, edit: true, delete: false, export: true },
      leads: { view: true, create: true, edit: true, delete: false, export: true },
      opportunities: { view: true, create: true, edit: true, delete: false, export: true },
      presales: { view: true, create: true, edit: true, delete: false, export: true },
      cases: { view: true, create: true, edit: true, delete: false, export: true },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 9,
    name: 'Sales Executive',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseOrders: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseRequisitions: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseReturns: { view: false, create: false, edit: false, delete: false, export: false },
      salesOrders: { view: true, create: true, edit: true, delete: false, export: true },
      salesQuotations: { view: true, create: true, edit: true, delete: false, export: true },
      deliveryChallans: { view: true, create: false, edit: false, delete: false, export: true },
      salesReturns: { view: true, create: false, edit: false, delete: false, export: true },
      customers: { view: true, create: true, edit: true, delete: false, export: true },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: false, create: false, edit: false, delete: false, export: false },
      productionOrders: { view: false, create: false, edit: false, delete: false, export: false },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: false, create: false, edit: false, delete: false, export: false },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: true, create: true, edit: true, delete: false, export: true },
      contacts: { view: true, create: true, edit: true, delete: false, export: true },
      leads: { view: true, create: true, edit: true, delete: false, export: true },
      opportunities: { view: true, create: true, edit: true, delete: false, export: true },
      presales: { view: true, create: true, edit: true, delete: false, export: true },
      cases: { view: true, create: true, edit: true, delete: false, export: true },
      reports: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 10,
    name: 'Production Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: true, edit: true, delete: false, export: true },
      categories: { view: true, create: true, edit: true, delete: false, export: true },
      units: { view: true, create: true, edit: true, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseRequisitions: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseReturns: { view: true, create: false, edit: false, delete: false, export: true },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: true, edit: true, delete: false, export: true },
      bom: { view: true, create: true, edit: true, delete: false, export: true },
      productionOrders: { view: true, create: true, edit: true, delete: false, export: true },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: true, create: true, edit: true, delete: false, export: true },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 11,
    name: 'Production Supervisor',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseRequisitions: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseReturns: { view: true, create: false, edit: false, delete: false, export: true },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: true, create: false, edit: true, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: true, delete: false, export: true },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: true, create: false, edit: true, delete: false, export: true },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 12,
    name: 'Production Operator',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseRequisitions: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseReturns: { view: true, create: false, edit: false, delete: false, export: true },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: true, create: false, edit: false, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: true, delete: false, export: true },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: false, create: false, edit: false, delete: false, export: false },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: false, edit: false, delete: false, export: false }
    }
  },
  {
    id: 13,
    name: 'Quality Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: true, edit: true, delete: false, export: true },
      categories: { view: true, create: true, edit: true, delete: false, export: true },
      units: { view: true, create: true, edit: true, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseRequisitions: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseReturns: { view: true, create: false, edit: false, delete: false, export: true },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: true, create: false, edit: false, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: false, delete: false, export: true },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: true, create: true, edit: true, delete: false, export: true },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 14,
    name: 'Quality Inspector',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseRequisitions: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseReturns: { view: true, create: false, edit: false, delete: false, export: true },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: true, create: false, edit: false, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: false, delete: false, export: true },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: true, create: true, edit: true, delete: false, export: true },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 15,
    name: 'Finance Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseRequisitions: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseReturns: { view: true, create: false, edit: false, delete: false, export: true },
      salesOrders: { view: true, create: false, edit: false, delete: false, export: true },
      salesQuotations: { view: true, create: false, edit: false, delete: false, export: true },
      deliveryChallans: { view: true, create: false, edit: false, delete: false, export: true },
      salesReturns: { view: true, create: false, edit: false, delete: false, export: true },
      customers: { view: true, create: false, edit: false, delete: false, export: true },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: true, create: false, edit: false, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: false, delete: false, export: true },
      expenses: { view: true, create: true, edit: true, delete: false, export: true },
      approvals: { view: true, create: true, edit: true, delete: false, export: true },
      dataImportExport: { view: true, create: false, edit: false, delete: false, export: true },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: true, create: false, edit: false, delete: false, export: true },
      contacts: { view: true, create: false, edit: false, delete: false, export: true },
      leads: { view: true, create: false, edit: false, delete: false, export: true },
      opportunities: { view: true, create: false, edit: false, delete: false, export: true },
      presales: { view: true, create: false, edit: false, delete: false, export: true },
      cases: { view: true, create: false, edit: false, delete: false, export: true },
      reports: { view: true, create: true, edit: true, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 16,
    name: 'Accountant',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseOrders: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseRequisitions: { view: true, create: false, edit: false, delete: false, export: true },
      purchaseReturns: { view: true, create: false, edit: false, delete: false, export: true },
      salesOrders: { view: true, create: false, edit: false, delete: false, export: true },
      salesQuotations: { view: true, create: false, edit: false, delete: false, export: true },
      deliveryChallans: { view: true, create: false, edit: false, delete: false, export: true },
      salesReturns: { view: true, create: false, edit: false, delete: false, export: true },
      customers: { view: true, create: false, edit: false, delete: false, export: true },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: true, create: false, edit: false, delete: false, export: true },
      productionOrders: { view: true, create: false, edit: false, delete: false, export: true },
      expenses: { view: true, create: true, edit: true, delete: false, export: true },
      approvals: { view: true, create: false, edit: false, delete: false, export: true },
      dataImportExport: { view: true, create: false, edit: false, delete: false, export: true },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: true, create: false, edit: false, delete: false, export: true },
      contacts: { view: true, create: false, edit: false, delete: false, export: true },
      leads: { view: true, create: false, edit: false, delete: false, export: true },
      opportunities: { view: true, create: false, edit: false, delete: false, export: true },
      presales: { view: true, create: false, edit: false, delete: false, export: true },
      cases: { view: true, create: false, edit: false, delete: false, export: true },
      reports: { view: true, create: true, edit: true, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 17,
    name: 'CRM Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseOrders: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseRequisitions: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseReturns: { view: false, create: false, edit: false, delete: false, export: false },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: false, create: false, edit: false, delete: false, export: false },
      productionOrders: { view: false, create: false, edit: false, delete: false, export: false },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: false, create: false, edit: false, delete: false, export: false },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: true, create: true, edit: true, delete: false, export: true },
      contacts: { view: true, create: true, edit: true, delete: false, export: true },
      leads: { view: true, create: true, edit: true, delete: false, export: true },
      opportunities: { view: true, create: true, edit: true, delete: false, export: true },
      presales: { view: true, create: true, edit: true, delete: false, export: true },
      cases: { view: true, create: true, edit: true, delete: false, export: true },
      reports: { view: true, create: true, edit: true, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 18,
    name: 'CRM Executive',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: true, create: false, edit: false, delete: false, export: true },
      categories: { view: true, create: false, edit: false, delete: false, export: true },
      units: { view: true, create: false, edit: false, delete: false, export: true },
      warehouses: { view: true, create: false, edit: false, delete: false, export: true },
      stock: { view: true, create: false, edit: false, delete: false, export: true },
      stockMovements: { view: true, create: false, edit: false, delete: false, export: true },
      suppliers: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseOrders: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseRequisitions: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseReturns: { view: false, create: false, edit: false, delete: false, export: false },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: true, create: false, edit: false, delete: false, export: true },
      bom: { view: false, create: false, edit: false, delete: false, export: false },
      productionOrders: { view: false, create: false, edit: false, delete: false, export: false },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: false, create: false, edit: false, delete: false, export: false },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: true, create: true, edit: true, delete: false, export: true },
      contacts: { view: true, create: true, edit: true, delete: false, export: true },
      leads: { view: true, create: true, edit: true, delete: false, export: true },
      opportunities: { view: true, create: true, edit: true, delete: false, export: true },
      presales: { view: true, create: true, edit: true, delete: false, export: true },
      cases: { view: true, create: true, edit: true, delete: false, export: true },
      reports: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 19,
    name: 'HR Manager',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: true },
      users: { view: true, create: true, edit: true, delete: false, export: true },
      roles: { view: true, create: false, edit: false, delete: false, export: true },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: false, create: false, edit: false, delete: false, export: false },
      categories: { view: false, create: false, edit: false, delete: false, export: false },
      units: { view: false, create: false, edit: false, delete: false, export: false },
      warehouses: { view: false, create: false, edit: false, delete: false, export: false },
      stock: { view: false, create: false, edit: false, delete: false, export: false },
      stockMovements: { view: false, create: false, edit: false, delete: false, export: false },
      suppliers: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseOrders: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseRequisitions: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseReturns: { view: false, create: false, edit: false, delete: false, export: false },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: false, create: false, edit: false, delete: false, export: false },
      bom: { view: false, create: false, edit: false, delete: false, export: false },
      productionOrders: { view: false, create: false, edit: false, delete: false, export: false },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: false, create: false, edit: false, delete: false, export: false },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: true, create: false, edit: false, delete: false, export: true },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: true, edit: true, delete: false, export: false }
    }
  },
  {
    id: 20,
    name: 'Employee',
    permissions: {
      dashboard: { view: true, create: false, edit: false, delete: false, export: false },
      users: { view: false, create: false, edit: false, delete: false, export: false },
      roles: { view: false, create: false, edit: false, delete: false, export: false },
      companies: { view: false, create: false, edit: false, delete: false, export: false },
      products: { view: false, create: false, edit: false, delete: false, export: false },
      categories: { view: false, create: false, edit: false, delete: false, export: false },
      units: { view: false, create: false, edit: false, delete: false, export: false },
      warehouses: { view: false, create: false, edit: false, delete: false, export: false },
      stock: { view: false, create: false, edit: false, delete: false, export: false },
      stockMovements: { view: false, create: false, edit: false, delete: false, export: false },
      suppliers: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseOrders: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseRequisitions: { view: false, create: false, edit: false, delete: false, export: false },
      purchaseReturns: { view: false, create: false, edit: false, delete: false, export: false },
      salesOrders: { view: false, create: false, edit: false, delete: false, export: false },
      salesQuotations: { view: false, create: false, edit: false, delete: false, export: false },
      deliveryChallans: { view: false, create: false, edit: false, delete: false, export: false },
      salesReturns: { view: false, create: false, edit: false, delete: false, export: false },
      customers: { view: false, create: false, edit: false, delete: false, export: false },
      brands: { view: false, create: false, edit: false, delete: false, export: false },
      bom: { view: false, create: false, edit: false, delete: false, export: false },
      productionOrders: { view: false, create: false, edit: false, delete: false, export: false },
      expenses: { view: false, create: false, edit: false, delete: false, export: false },
      approvals: { view: false, create: false, edit: false, delete: false, export: false },
      dataImportExport: { view: false, create: false, edit: false, delete: false, export: false },
      racks: { view: false, create: false, edit: false, delete: false, export: false },
      bins: { view: false, create: false, edit: false, delete: false, export: false },
      accounts: { view: false, create: false, edit: false, delete: false, export: false },
      contacts: { view: false, create: false, edit: false, delete: false, export: false },
      leads: { view: false, create: false, edit: false, delete: false, export: false },
      opportunities: { view: false, create: false, edit: false, delete: false, export: false },
      presales: { view: false, create: false, edit: false, delete: false, export: false },
      cases: { view: false, create: false, edit: false, delete: false, export: false },
      reports: { view: false, create: false, edit: false, delete: false, export: false },
      settings: { view: false, create: false, edit: false, delete: false, export: false },
      chat: { view: true, create: false, edit: false, delete: false, export: false }
    }
  }
];

const seedRoles = async () => {
  const client = await appPool.connect();
  
  try {
    console.log('🌱 Starting role seeding...\n');
    
    let insertedCount = 0;
    let updatedCount = 0;
    
    for (const role of ROLES) {
      const result = await client.query(
        `INSERT INTO "Roles" ("Id", "RoleName", "IsActive", "Permissions", "CreatedAt", "UpdatedAt")
         VALUES ($1, $2, TRUE, $3, NOW(), NOW())
         ON CONFLICT ("Id") 
         DO UPDATE SET 
           "RoleName" = EXCLUDED."RoleName",
           "Permissions" = EXCLUDED."Permissions",
           "UpdatedAt" = NOW()
         RETURNING "Id", "RoleName"`,
        [role.id, role.name, JSON.stringify(role.permissions)]
      );
      
      const row = result.rows[0];
      console.log(`✓ ${row.RoleName} (ID: ${row.Id})`);
      
      if (result.rows.length > 0 && result.command === 'INSERT') {
        insertedCount++;
      } else {
        updatedCount++;
      }
    }
    
    console.log(`\n✅ Role seeding completed!`);
    console.log(`   Inserted: ${insertedCount} roles`);
    console.log(`   Updated: ${updatedCount} roles`);
    console.log(`   Total: ${ROLES.length} roles\n`);
    
  } catch (error) {
    console.error('❌ Error seeding roles:', error);
    process.exit(1);
  } finally {
    client.release();
    await appPool.end();
  }
};

// Run if called directly
if (require.main === module) {
  seedRoles()
    .then(() => {
      console.log('✨ Done!');
      process.exit(0);
    })
    .catch((error) => {
      console.error('Fatal error:', error);
      process.exit(1);
    });
}

module.exports = { seedRoles, ROLES };